import type { IngestOptions } from "./base/types";

export const DEFAULT_USER_AGENT =
  "ShopScoutBot/1.0 (+https://shopscout.app; product-discovery; respects-robots)";

export const DEFAULT_INGEST: Required<
  Pick<
    IngestOptions,
    "maxPerRetailer" | "concurrency" | "discoverLimit" | "validateLinks" | "incremental" | "chunkSize"
  >
> = {
  maxPerRetailer: 120,
  concurrency: 5,
  discoverLimit: 250,
  validateLinks: true,
  incremental: false,
  chunkSize: 250,
};

/** High-success retailers — ingest these first. */
export const PRIORITY_RETAILERS = [
  "walmart",
  "target",
  "costco",
  "wayfair",
  "kohls",
  "macys",
  "nike",
  "gap",
  "oldnavy",
  "bestbuy",
] as const;

/** Retailers with existing HTML adapters (search → real PDP). */
export const ADAPTER_RETAILERS = [
  "walmart",
  "target",
  "amazon",
  "kroger",
  "costco",
  "aldi",
] as const;

/** Domains for retailers not in url-parser (slug used in catalog). */
export const EXTRA_RETAILER_DOMAINS: Record<string, string> = {
  bestbuy: "bestbuy.com",
  homedepot: "homedepot.com",
  lowes: "lowes.com",
  sephora: "sephora.com",
  ulta: "ulta.com",
};

export const RETAILER_SEEDS: Record<
  string,
  { sitemap?: string; categories?: string[] }
> = {
  walmart: {
    sitemap: "https://www.walmart.com/sitemap_index.xml",
    categories: [
      "https://www.walmart.com/browse/food/976759_976787",
      "https://www.walmart.com/browse/household-essentials/1115193",
    ],
  },
  target: {
    sitemap: "https://www.target.com/sitemap_index.xml",
    categories: [
      "https://www.target.com/c/grocery/-/N-5xtg6",
      "https://www.target.com/c/household-essentials/-/N-5xsxr",
    ],
  },
  costco: {
    categories: [
      "https://www.costco.com/grocery-household.html",
      "https://www.costco.com/snacks.html",
    ],
  },
  wayfair: {
    sitemap: "https://www.wayfair.com/sitemap.xml",
    categories: ["https://www.wayfair.com/furniture/cat/furniture-c45974.html"],
  },
  kohls: {
    categories: [
      "https://www.kohls.com/catalog/mens-clothing.jsp",
      "https://www.kohls.com/catalog/womens-clothing.jsp",
    ],
  },
  macys: {
    categories: ["https://www.macys.com/shop/mens-clothing", "https://www.macys.com/shop/womens"],
  },
  nike: {
    categories: ["https://www.nike.com/w/mens-shoes-nik1zy7ok"],
  },
  bestbuy: {
    sitemap: "https://www.bestbuy.com/sitemap.xml",
    categories: ["https://www.bestbuy.com/site/electronics/cat/abcat0500000.c"],
  },
  homedepot: {
    categories: ["https://www.homedepot.com/b/Appliances/N-5yc1vZc3oi"],
  },
  lowes: {
    categories: ["https://www.lowes.com/c/Appliances"],
  },
  ikea: {
    categories: ["https://www.ikea.com/us/en/cat/products-products/"],
  },
  sephora: {
    categories: ["https://www.sephora.com/shop/makeup-cosmetics"],
  },
  ulta: {
    categories: ["https://www.ulta.com/shop/makeup"],
  },
  amazon: {
    categories: [
      "https://www.amazon.com/gp/bestsellers/grocery",
      "https://www.amazon.com/gp/bestsellers/home-garden",
    ],
  },
};

export const PILOT_RETAILERS = PRIORITY_RETAILERS;

/** Extra search queries beyond catalog (adapter ingest). */
export const BULK_SEARCH_QUERIES = [
  "whole milk",
  "organic eggs",
  "paper towels",
  "laundry detergent",
  "ground coffee",
  "chicken breast",
  "olive oil",
  "pasta sauce",
  "granola bars",
  "bottled water",
  "dish soap",
  "toilet paper",
  "cheddar cheese",
  "greek yogurt",
  "bananas",
  "apples",
  "frozen pizza",
  "ice cream",
  "cereal",
  "peanut butter",
  "wireless earbuds",
  "bluetooth speaker",
  "air fryer",
  "vacuum cleaner",
  "running shoes",
  "mens jeans",
  "womens hoodie",
  "bed sheets",
  "throw pillows",
  "desk lamp",
  "shampoo",
  "body wash",
  "sunscreen",
  "vitamin c",
  "protein powder",
  "dog food",
  "cat litter",
  "baby diapers",
  "coffee maker",
  "stand mixer",
  "nonstick pan",
  "storage bins",
  "LED light bulbs",
  "phone charger",
  "laptop sleeve",
  "backpack",
  "sunglasses",
  "watch",
  "hand soap",
  "all purpose cleaner",
  "trash bags",
  "aluminum foil",
  "sandwich bags",
  "sparkling water",
  "orange juice",
  "butter",
  "sour cream",
  "bagels",
  "tortillas",
  "salsa",
  "chips",
  "cookies",
  "dark chocolate",
  "green tea",
  "oat milk",
  "almond butter",
  "honey",
  "maple syrup",
  "rice",
  "black beans",
  "chicken broth",
  "tomato soup",
  "tuna",
  "salmon fillet",
  "ground beef",
  "bacon",
  "bagged salad",
  "broccoli",
  "carrots",
  "onions",
  "potatoes",
  "avocado",
  "strawberries",
  "blueberries",
  "lemons",
  "garlic",
  "ginger",
  "cinnamon",
  "vanilla extract",
  "flour",
  "sugar",
  "baking soda",
  "chocolate chips",
  "pancake mix",
  "instant oatmeal",
  "granola",
  "trail mix",
  "beef jerky",
  "crackers",
  "pretzels",
  "popcorn",
  "soda",
  "energy drink",
  "kombucha",
  "beer",
  "wine",
  "paper plates",
  "plastic cups",
  "napkins",
  "foil pans",
  "charcoal",
  "lighter fluid",
  "insect repellent",
  "sun hat",
  "beach towel",
  "cooler",
  "camping chair",
  "hiking boots",
  "rain jacket",
  "umbrella",
  "gloves",
  "scarf",
  "belt",
  "wallet",
  "socks",
  "underwear",
  "bras",
  "pajamas",
  "slippers",
  "robe",
  "towel set",
  "shower curtain",
  "bath mat",
  "toothpaste",
  "toothbrush",
  "floss",
  "mouthwash",
  "deodorant",
  "razor",
  "shaving cream",
  "lotion",
  "face wash",
  "moisturizer",
  "lip balm",
  "makeup remover",
  "foundation",
  "mascara",
  "lipstick",
  "nail polish",
  "hair dryer",
  "curling iron",
  "hair ties",
  "bobby pins",
  "comb",
  "brush",
  "cotton swabs",
  "tissues",
  "bandages",
  "pain reliever",
  "allergy medicine",
  "cough drops",
  "thermometer",
  "heating pad",
  "ice pack",
  "yoga mat",
  "dumbbells",
  "resistance bands",
  "water bottle",
  "gym bag",
  "fitness tracker",
  "bike helmet",
  "skateboard",
  "basketball",
  "soccer ball",
  "tennis balls",
  "golf balls",
  "fishing line",
  "tent",
  "sleeping bag",
  "flashlight",
  "batteries",
  "extension cord",
  "power strip",
  "USB cable",
  "HDMI cable",
  "router",
  "keyboard",
  "mouse",
  "monitor",
  "webcam",
  "printer ink",
  "notebook",
  "pens",
  "markers",
  "stapler",
  "tape",
  "scissors",
  "glue sticks",
  "folder",
  "binder",
  "calendar",
  "picture frame",
  "wall clock",
  "area rug",
  "curtains",
  "blinds",
  "coat rack",
  "shoe rack",
  "hangers",
  "laundry basket",
  "ironing board",
  "steamer",
  "sewing kit",
  "duct tape",
  "wd-40",
  "screwdriver set",
  "hammer",
  "drill",
  "paint brush",
  "interior paint",
  "light switch",
  "smoke detector",
  "fire extinguisher",
  "first aid kit",
  "car air freshener",
  "windshield wipers",
  "motor oil",
  "jumper cables",
  "tire inflator",
  "phone mount",
  "dash cam",
];
