import type { RetailerMeta } from "./meta";

/** Grocery & delivery with shoppable product search */
export const GROCERY_EXTRA_RETAILERS: RetailerMeta[] = [
  {
    id: "albertsons",
    name: "Albertsons",
    shortName: "Albertsons",
    color: "#004B87",
    tagline: "Neighborhood grocery",
    types: ["grocery", "general"],
  },
  {
    id: "safeway",
    name: "Safeway",
    shortName: "Safeway",
    color: "#E31837",
    tagline: "Fresh groceries",
    types: ["grocery", "general"],
  },
  {
    id: "vons",
    name: "Vons",
    shortName: "Vons",
    color: "#E31837",
    tagline: "West coast grocery",
    types: ["grocery"],
  },
  {
    id: "jewelosco",
    name: "Jewel-Osco",
    shortName: "Jewel-Osco",
    color: "#E31837",
    tagline: "Midwest grocery",
    types: ["grocery"],
  },
  {
    id: "sprouts",
    name: "Sprouts",
    shortName: "Sprouts",
    color: "#3D7C3F",
    tagline: "Natural & organic",
    types: ["grocery", "general"],
  },
  {
    id: "wholefoods",
    name: "Whole Foods Market",
    shortName: "Whole Foods",
    color: "#00674F",
    tagline: "Organic grocery",
    types: ["grocery", "general"],
  },
  {
    id: "heb",
    name: "H-E-B",
    shortName: "H-E-B",
    color: "#EE3124",
    tagline: "Texas grocery",
    types: ["grocery", "general"],
  },
  {
    id: "meijer",
    name: "Meijer",
    shortName: "Meijer",
    color: "#D4232A",
    tagline: "Supercenter",
    types: ["grocery", "general", "clothing"],
  },
  {
    id: "hyvee",
    name: "Hy-Vee",
    shortName: "Hy-Vee",
    color: "#E21E2D",
    tagline: "Midwest supermarket",
    types: ["grocery", "general"],
  },
  {
    id: "wegmans",
    name: "Wegmans",
    shortName: "Wegmans",
    color: "#C8102E",
    tagline: "Premium grocery",
    types: ["grocery", "general"],
  },
  {
    id: "stopandshop",
    name: "Stop & Shop",
    shortName: "Stop & Shop",
    color: "#00843D",
    tagline: "Northeast grocery",
    types: ["grocery"],
  },
  {
    id: "giantfood",
    name: "Giant Food",
    shortName: "Giant",
    color: "#6A1B9A",
    tagline: "East coast grocery",
    types: ["grocery"],
  },
  {
    id: "weismarkets",
    name: "Weis Markets",
    shortName: "Weis",
    color: "#C41230",
    tagline: "Regional grocery",
    types: ["grocery"],
  },
  {
    id: "freshdirect",
    name: "FreshDirect",
    shortName: "FreshDirect",
    color: "#FF6B00",
    tagline: "Online grocery delivery",
    types: ["grocery"],
  },
  {
    id: "thrivemarket",
    name: "Thrive Market",
    shortName: "Thrive",
    color: "#2D5A27",
    tagline: "Organic marketplace",
    types: ["grocery", "general"],
  },
  {
    id: "boxed",
    name: "Boxed",
    shortName: "Boxed",
    color: "#1A1A1A",
    tagline: "Bulk grocery online",
    types: ["grocery", "general"],
  },
  {
    id: "shipt",
    name: "Shipt",
    shortName: "Shipt",
    color: "#00B140",
    tagline: "Same-day delivery",
    types: ["grocery", "general"],
  },
];
