import type { RetailerMeta } from "./meta";

/** Kids & baby specialty retailers (mass-market chains like Target/Walmart already in core list). */
export const KIDS_EXTRA_RETAILERS: RetailerMeta[] = [
  {
    id: "potterybarnkids",
    name: "Pottery Barn Kids",
    shortName: "PB Kids",
    color: "#8B7355",
    tagline: "Kids furniture & décor",
    types: ["home", "clothing", "general"],
  },
  {
    id: "gerber",
    name: "Gerber Childrenswear",
    shortName: "Gerber",
    color: "#005EB8",
    tagline: "Baby basics",
    types: ["clothing"],
  },
  {
    id: "buybuybaby",
    name: "Buy Buy Baby",
    shortName: "Buy Buy Baby",
    color: "#6B2D5B",
    tagline: "Baby gear & nursery",
    types: ["general", "home"],
  },
  {
    id: "hannaandersson",
    name: "Hanna Andersson",
    shortName: "Hanna",
    color: "#C41E3A",
    tagline: "Organic kids wear",
    types: ["clothing"],
  },
  {
    id: "primary",
    name: "Primary",
    shortName: "Primary",
    color: "#FF6B6B",
    tagline: "Colorful kids basics",
    types: ["clothing"],
  },
  {
    id: "monicaandandy",
    name: "Monica + Andy",
    shortName: "M+A",
    color: "#F4A6B8",
    tagline: "Organic baby apparel",
    types: ["clothing"],
  },
  {
    id: "kytebaby",
    name: "Kyte Baby",
    shortName: "Kyte Baby",
    color: "#7EC8C8",
    tagline: "Bamboo baby sleepwear",
    types: ["clothing"],
  },
  {
    id: "crateandkids",
    name: "Crate & Kids",
    shortName: "Crate & Kids",
    color: "#1A1A1A",
    tagline: "Modern kids home",
    types: ["home", "clothing", "general"],
  },
  {
    id: "littlesleepies",
    name: "Little Sleepies",
    shortName: "Little Sleepies",
    color: "#B8A9E8",
    tagline: "Soft zip rompers",
    types: ["clothing"],
  },
  {
    id: "poshpeanut",
    name: "Posh Peanut",
    shortName: "Posh Peanut",
    color: "#E8B4CB",
    tagline: "Bamboo kids fashion",
    types: ["clothing"],
  },
  {
    id: "maisonette",
    name: "Maisonette",
    shortName: "Maisonette",
    color: "#2C2C2C",
    tagline: "Curated kids marketplace",
    types: ["clothing", "general"],
  },
  {
    id: "janieandjack",
    name: "Janie and Jack",
    shortName: "Janie and Jack",
    color: "#1E3A5F",
    tagline: "Upscale kids fashion",
    types: ["clothing", "shoes"],
  },
  {
    id: "gymboree",
    name: "Gymboree",
    shortName: "Gymboree",
    color: "#E31937",
    tagline: "Playful kids styles",
    types: ["clothing"],
  },
  {
    id: "honest",
    name: "The Honest Company",
    shortName: "Honest",
    color: "#00A376",
    tagline: "Baby & home essentials",
    types: ["general", "clothing"],
  },
  {
    id: "burtsbeesbaby",
    name: "Burt's Bees Baby",
    shortName: "Burt's Bees Baby",
    color: "#F5C518",
    tagline: "Organic cotton baby",
    types: ["clothing"],
  },
  {
    id: "albeebaby",
    name: "Albee Baby",
    shortName: "Albee Baby",
    color: "#0066B3",
    tagline: "Strollers & gear",
    types: ["general"],
  },
  {
    id: "marshalls",
    name: "Marshalls",
    shortName: "Marshalls",
    color: "#CC0000",
    tagline: "Off-price family fashion",
    types: ["clothing", "shoes", "general"],
  },
];
