import type { RetailerMeta } from "./meta";

/** Additional fashion & kids retailers with reliable search URLs */
export const FASHION_EXTRA_RETAILERS: RetailerMeta[] = [
  {
    id: "nordstrom",
    name: "Nordstrom",
    shortName: "Nordstrom",
    color: "#1B1B1B",
    tagline: "Designer fashion",
    types: ["clothing", "shoes", "general"],
  },
  {
    id: "nordstromrack",
    name: "Nordstrom Rack",
    shortName: "Rack",
    color: "#C8102E",
    tagline: "Off-price fashion",
    types: ["clothing", "shoes", "general"],
  },
  {
    id: "jcrew",
    name: "J.Crew",
    shortName: "J.Crew",
    color: "#0A3D62",
    tagline: "Classic American style",
    types: ["clothing", "shoes", "general"],
  },
  {
    id: "anthropologie",
    name: "Anthropologie",
    shortName: "Anthro",
    color: "#8B4513",
    tagline: "Women's lifestyle",
    types: ["clothing", "home", "general"],
  },
  {
    id: "athleta",
    name: "Athleta",
    shortName: "Athleta",
    color: "#2C2C2C",
    tagline: "Women's activewear",
    types: ["clothing", "sports"],
  },
  {
    id: "patagonia",
    name: "Patagonia",
    shortName: "Patagonia",
    color: "#1C3C34",
    tagline: "Outdoor apparel",
    types: ["clothing", "sports", "general"],
  },
  {
    id: "rei",
    name: "REI",
    shortName: "REI",
    color: "#006341",
    tagline: "Outdoor gear",
    types: ["clothing", "shoes", "sports", "general"],
  },
  {
    id: "dillards",
    name: "Dillard's",
    shortName: "Dillard's",
    color: "#8B0000",
    tagline: "Department store",
    types: ["clothing", "shoes", "home", "general"],
  },
  {
    id: "bloomingdales",
    name: "Bloomingdale's",
    shortName: "Bloomingdale's",
    color: "#000000",
    tagline: "Luxury department",
    types: ["clothing", "shoes", "home", "general"],
  },
  {
    id: "childrensplace",
    name: "The Children's Place",
    shortName: "TCP",
    color: "#00A3E0",
    tagline: "Kids clothing",
    types: ["clothing", "shoes"],
  },
  {
    id: "carters",
    name: "Carter's",
    shortName: "Carter's",
    color: "#00A0DF",
    tagline: "Baby & kids",
    types: ["clothing"],
  },
  {
    id: "oshkosh",
    name: "OshKosh B'gosh",
    shortName: "OshKosh",
    color: "#FFD200",
    tagline: "Kids denim",
    types: ["clothing"],
  },
  {
    id: "shein",
    name: "SHEIN",
    shortName: "SHEIN",
    color: "#000000",
    tagline: "Fast fashion online",
    types: ["clothing", "shoes", "general"],
  },
  {
    id: "urbanoutfitters",
    name: "Urban Outfitters",
    shortName: "UO",
    color: "#1A1A1A",
    tagline: "Lifestyle fashion",
    types: ["clothing", "shoes", "home"],
  },
  {
    id: "forever21",
    name: "Forever 21",
    shortName: "F21",
    color: "#F9E900",
    tagline: "Trend fashion",
    types: ["clothing", "shoes", "general"],
  },
  {
    id: "llbean",
    name: "L.L.Bean",
    shortName: "L.L.Bean",
    color: "#006341",
    tagline: "Outdoor & casual",
    types: ["clothing", "shoes", "general"],
  },
  {
    id: "columbia",
    name: "Columbia",
    shortName: "Columbia",
    color: "#0072CE",
    tagline: "Outdoor sportswear",
    types: ["clothing", "shoes", "sports"],
  },
  {
    id: "skims",
    name: "SKIMS",
    shortName: "SKIMS",
    color: "#C4A484",
    tagline: "Solutionswear",
    types: ["clothing"],
  },
];
