import type { RetailerMeta } from "./meta";

/** Sports & outdoor specialty retailers (Nike, REI, Dick's, etc. already in core / fashion lists). */
export const SPORTS_EXTRA_RETAILERS: RetailerMeta[] = [
  {
    id: "basspro",
    name: "Bass Pro Shops",
    shortName: "Bass Pro",
    color: "#006341",
    tagline: "Hunting & fishing",
    types: ["sports", "general"],
  },
  {
    id: "cabelas",
    name: "Cabela's",
    shortName: "Cabela's",
    color: "#FF6600",
    tagline: "Outdoor outfitter",
    types: ["sports", "general"],
  },
  {
    id: "academy",
    name: "Academy Sports + Outdoors",
    shortName: "Academy",
    color: "#003366",
    tagline: "Sports & outdoors",
    types: ["sports", "clothing", "shoes"],
  },
  {
    id: "sportsmanswarehouse",
    name: "Sportsman's Warehouse",
    shortName: "Sportsman's",
    color: "#C8102E",
    tagline: "Hunting & camping",
    types: ["sports", "general"],
  },
  {
    id: "scheels",
    name: "Scheels",
    shortName: "Scheels",
    color: "#ED1C24",
    tagline: "All-sports superstore",
    types: ["sports", "clothing", "shoes"],
  },
  {
    id: "backcountry",
    name: "Backcountry",
    shortName: "Backcountry",
    color: "#000000",
    tagline: "Outdoor gear online",
    types: ["sports", "clothing"],
  },
  {
    id: "moosejaw",
    name: "Moosejaw",
    shortName: "Moosejaw",
    color: "#FF6600",
    tagline: "Outdoor & climbing",
    types: ["sports", "clothing"],
  },
  {
    id: "evo",
    name: "Evo",
    shortName: "Evo",
    color: "#111111",
    tagline: "Ski, skate, bike",
    types: ["sports", "clothing", "shoes"],
  },
  {
    id: "sierra",
    name: "Sierra",
    shortName: "Sierra",
    color: "#006633",
    tagline: "Outdoor outlet deals",
    types: ["sports", "clothing"],
  },
  {
    id: "big5",
    name: "Big 5 Sporting Goods",
    shortName: "Big 5",
    color: "#003087",
    tagline: "Value sporting goods",
    types: ["sports", "clothing", "shoes"],
  },
  {
    id: "hibbett",
    name: "Hibbett Sports",
    shortName: "Hibbett",
    color: "#E31837",
    tagline: "Athletic footwear",
    types: ["sports", "shoes", "clothing"],
  },
  {
    id: "dunhams",
    name: "Dunham's Sports",
    shortName: "Dunham's",
    color: "#003DA5",
    tagline: "Midwest sporting goods",
    types: ["sports", "clothing", "shoes"],
  },
  {
    id: "fleetfeet",
    name: "Fleet Feet",
    shortName: "Fleet Feet",
    color: "#E35205",
    tagline: "Running specialty",
    types: ["sports", "shoes"],
  },
  {
    id: "orvis",
    name: "Orvis",
    shortName: "Orvis",
    color: "#2F4F2F",
    tagline: "Fly fishing & apparel",
    types: ["sports", "clothing"],
  },
  {
    id: "westmarine",
    name: "West Marine",
    shortName: "West Marine",
    color: "#003087",
    tagline: "Boating & marine",
    types: ["sports", "general"],
  },
  {
    id: "campingworld",
    name: "Camping World",
    shortName: "Camping World",
    color: "#0054A4",
    tagline: "RV & camping gear",
    types: ["sports", "general"],
  },
  {
    id: "decathlon",
    name: "Decathlon",
    shortName: "Decathlon",
    color: "#0082C3",
    tagline: "Affordable sports gear",
    types: ["sports", "clothing", "shoes"],
  },
  {
    id: "publiclands",
    name: "Public Lands",
    shortName: "Public Lands",
    color: "#2D5016",
    tagline: "Outdoor community",
    types: ["sports", "clothing"],
  },
];
