import type { RetailerMeta } from "./meta";

/** Bags, luggage & additional luxury with product search */
export const BAGS_LUXURY_RETAILERS: RetailerMeta[] = [
  {
    id: "katespade",
    name: "Kate Spade New York",
    shortName: "Kate Spade",
    color: "#000000",
    tagline: "Handbags & accessories",
    types: ["clothing", "general"],
  },
  {
    id: "samsonite",
    name: "Samsonite",
    shortName: "Samsonite",
    color: "#C41230",
    tagline: "Luggage & travel",
    types: ["general"],
  },
  {
    id: "tumi",
    name: "Tumi",
    shortName: "Tumi",
    color: "#1A1A1A",
    tagline: "Premium luggage",
    types: ["general"],
  },
  {
    id: "longchamp",
    name: "Longchamp",
    shortName: "Longchamp",
    color: "#2D5016",
    tagline: "French leather goods",
    types: ["clothing", "general"],
  },
  {
    id: "marcjacobs",
    name: "Marc Jacobs",
    shortName: "Marc Jacobs",
    color: "#000000",
    tagline: "Designer bags",
    types: ["clothing", "general"],
  },
  {
    id: "toryburch",
    name: "Tory Burch",
    shortName: "Tory Burch",
    color: "#F4C4A0",
    tagline: "Accessible luxury",
    types: ["clothing", "shoes", "general"],
  },
  {
    id: "rimowa",
    name: "Rimowa",
    shortName: "Rimowa",
    color: "#8B8B8B",
    tagline: "Aluminum luggage",
    types: ["general"],
  },
  {
    id: "away",
    name: "Away",
    shortName: "Away",
    color: "#1A1A1A",
    tagline: "Modern luggage",
    types: ["general"],
  },
  {
    id: "herschel",
    name: "Herschel Supply Co.",
    shortName: "Herschel",
    color: "#1A1A1A",
    tagline: "Backpacks & bags",
    types: ["clothing", "general"],
  },
  {
    id: "jansport",
    name: "JanSport",
    shortName: "JanSport",
    color: "#003DA5",
    tagline: "Backpacks",
    types: ["clothing", "general", "sports"],
  },
  {
    id: "fjallraven",
    name: "Fjällräven",
    shortName: "Fjällräven",
    color: "#2D4A3E",
    tagline: "Outdoor packs",
    types: ["clothing", "sports", "general"],
  },
  {
    id: "dagnedover",
    name: "Dagne Dover",
    shortName: "Dagne Dover",
    color: "#1A1A1A",
    tagline: "Modern bags",
    types: ["clothing", "general"],
  },
  {
    id: "beis",
    name: "Béis",
    shortName: "Béis",
    color: "#C4A484",
    tagline: "Travel & baby bags",
    types: ["clothing", "general"],
  },
  {
    id: "verabradley",
    name: "Vera Bradley",
    shortName: "Vera Bradley",
    color: "#5C2D91",
    tagline: "Quilted bags",
    types: ["clothing", "general"],
  },
  {
    id: "mcm",
    name: "MCM",
    shortName: "MCM",
    color: "#C9A227",
    tagline: "Luxury leather",
    types: ["clothing", "general"],
  },
  {
    id: "bottegaveneta",
    name: "Bottega Veneta",
    shortName: "Bottega",
    color: "#1B5E3C",
    tagline: "Italian luxury",
    types: ["clothing", "shoes", "general"],
  },
  {
    id: "saintlaurent",
    name: "Saint Laurent",
    shortName: "YSL",
    color: "#000000",
    tagline: "Parisian luxury",
    types: ["clothing", "shoes", "general"],
  },
];
