import type { RetailerMeta } from "./meta";

/** Bookstores & bedding/home — merged into main retailer list */
export const BOOKS_HOME_RETAILERS: RetailerMeta[] = [
  // Books
  {
    id: "barnesnoble",
    name: "Barnes & Noble",
    shortName: "B&N",
    color: "#2D4A3E",
    tagline: "Books & more",
    types: ["books", "general"],
  },
  {
    id: "indigo",
    name: "Indigo",
    shortName: "Indigo",
    color: "#1C3664",
    tagline: "Books & lifestyle",
    types: ["books", "general"],
  },
  {
    id: "waterstones",
    name: "Waterstones",
    shortName: "Waterstones",
    color: "#2F3A56",
    tagline: "British bookseller",
    types: ["books"],
  },
  {
    id: "abebooks",
    name: "AbeBooks",
    shortName: "AbeBooks",
    color: "#B22222",
    tagline: "Used & rare books",
    types: ["books"],
  },
  {
    id: "fnac",
    name: "Fnac",
    shortName: "Fnac",
    color: "#E8A400",
    tagline: "Books & media",
    types: ["books", "general"],
  },
  {
    id: "whsmith",
    name: "WHSmith",
    shortName: "WHSmith",
    color: "#005EB8",
    tagline: "Books & stationery",
    types: ["books", "general"],
  },
  {
    id: "kinokuniya",
    name: "Kinokuniya",
    shortName: "Kinokuniya",
    color: "#1A5276",
    tagline: "Japanese bookstore",
    types: ["books"],
  },
  {
    id: "booksamillion",
    name: "Books-A-Million",
    shortName: "BAM",
    color: "#003366",
    tagline: "Books & gifts",
    types: ["books", "general"],
  },
  {
    id: "powells",
    name: "Powell's Books",
    shortName: "Powell's",
    color: "#7A3030",
    tagline: "Independent bookstore",
    types: ["books"],
  },
  {
    id: "bookshop",
    name: "Bookshop.org",
    shortName: "Bookshop",
    color: "#2C5F4F",
    tagline: "Support local bookstores",
    types: ["books"],
  },
  {
    id: "worldofbooks",
    name: "World of Books",
    shortName: "World of Books",
    color: "#3D6B4F",
    tagline: "Used books online",
    types: ["books"],
  },
  {
    id: "alibris",
    name: "Alibris",
    shortName: "Alibris",
    color: "#C75B12",
    tagline: "New & used books",
    types: ["books"],
  },
  {
    id: "betterworldbooks",
    name: "Better World Books",
    shortName: "Better World",
    color: "#2E7D32",
    tagline: "Used books for good",
    types: ["books"],
  },
  {
    id: "halfpricebooks",
    name: "Half Price Books",
    shortName: "HPB",
    color: "#FFD100",
    tagline: "New & used books",
    types: ["books", "general"],
  },
  {
    id: "dymocks",
    name: "Dymocks",
    shortName: "Dymocks",
    color: "#C41E3A",
    tagline: "Australian bookseller",
    types: ["books"],
  },
  {
    id: "strand",
    name: "The Strand",
    shortName: "Strand",
    color: "#8B0000",
    tagline: "NYC bookstore",
    types: ["books"],
  },
  {
    id: "bookoutlet",
    name: "Book Outlet",
    shortName: "Book Outlet",
    color: "#E65100",
    tagline: "Discount books",
    types: ["books"],
  },
  // Bedding & home
  {
    id: "wayfair",
    name: "Wayfair",
    shortName: "Wayfair",
    color: "#7B189F",
    tagline: "Home & furniture",
    types: ["home", "bedding", "general"],
  },
  {
    id: "mattressfirm",
    name: "Mattress Firm",
    shortName: "Mattress Firm",
    color: "#E31837",
    tagline: "Sleep experts",
    types: ["bedding", "home"],
  },
  {
    id: "sleepnumber",
    name: "Sleep Number",
    shortName: "Sleep Number",
    color: "#0054A6",
    tagline: "Adjustable sleep",
    types: ["bedding", "home"],
  },
  {
    id: "ashley",
    name: "Ashley Furniture",
    shortName: "Ashley",
    color: "#FF6600",
    tagline: "Furniture & mattresses",
    types: ["home", "bedding"],
  },
  {
    id: "brooklinen",
    name: "Brooklinen",
    shortName: "Brooklinen",
    color: "#1A3A52",
    tagline: "Luxury bedding",
    types: ["bedding", "home"],
  },
  {
    id: "bollbranch",
    name: "Boll & Branch",
    shortName: "Boll & Branch",
    color: "#2F4F4F",
    tagline: "Organic bedding",
    types: ["bedding", "home"],
  },
  {
    id: "saatva",
    name: "Saatva",
    shortName: "Saatva",
    color: "#1B4332",
    tagline: "Luxury mattresses",
    types: ["bedding", "home"],
  },
  {
    id: "purple",
    name: "Purple",
    shortName: "Purple",
    color: "#7B2D8E",
    tagline: "Grid mattresses",
    types: ["bedding", "home"],
  },
  {
    id: "casper",
    name: "Casper",
    shortName: "Casper",
    color: "#1D3557",
    tagline: "Sleep products",
    types: ["bedding", "home"],
  },
  {
    id: "nectar",
    name: "Nectar",
    shortName: "Nectar",
    color: "#F4A261",
    tagline: "Memory foam sleep",
    types: ["bedding", "home"],
  },
  {
    id: "dreamcloud",
    name: "DreamCloud",
    shortName: "DreamCloud",
    color: "#264653",
    tagline: "Hybrid luxury sleep",
    types: ["bedding", "home"],
  },
  {
    id: "parachute",
    name: "Parachute Home",
    shortName: "Parachute",
    color: "#4A4A4A",
    tagline: "Home essentials",
    types: ["bedding", "home"],
  },
  {
    id: "cozyearth",
    name: "Cozy Earth",
    shortName: "Cozy Earth",
    color: "#8B7355",
    tagline: "Bamboo bedding",
    types: ["bedding", "home"],
  },
  {
    id: "potterybarn",
    name: "Pottery Barn",
    shortName: "Pottery Barn",
    color: "#6B5B4F",
    tagline: "Home furnishings",
    types: ["home", "bedding", "general"],
  },
  {
    id: "westelm",
    name: "West Elm",
    shortName: "West Elm",
    color: "#3D3D3D",
    tagline: "Modern home",
    types: ["home", "bedding", "general"],
  },
  {
    id: "ikea",
    name: "IKEA",
    shortName: "IKEA",
    color: "#0058A3",
    tagline: "Affordable home",
    types: ["home", "bedding", "general"],
  },
  {
    id: "quince",
    name: "Quince",
    shortName: "Quince",
    color: "#1C1C1C",
    tagline: "Direct luxury home",
    types: ["bedding", "home", "clothing"],
  },
  {
    id: "avocado",
    name: "Avocado",
    shortName: "Avocado",
    color: "#3D5C3A",
    tagline: "Organic mattresses",
    types: ["bedding", "home"],
  },
  {
    id: "helix",
    name: "Helix Sleep",
    shortName: "Helix",
    color: "#00A0DC",
    tagline: "Custom mattresses",
    types: ["bedding", "home"],
  },
  {
    id: "brooklynbedding",
    name: "Brooklyn Bedding",
    shortName: "Brooklyn Bedding",
    color: "#2C3E50",
    tagline: "Mattresses made in USA",
    types: ["bedding", "home"],
  },
  {
    id: "frette",
    name: "Frette",
    shortName: "Frette",
    color: "#1A1A1A",
    tagline: "Italian linens",
    types: ["bedding", "home"],
  },
  {
    id: "sferra",
    name: "Sferra",
    shortName: "Sferra",
    color: "#4A3728",
    tagline: "Luxury linens",
    types: ["bedding", "home"],
  },
  {
    id: "peacockalley",
    name: "Peacock Alley",
    shortName: "Peacock Alley",
    color: "#1E4D6B",
    tagline: "Fine linens",
    types: ["bedding", "home"],
  },
  {
    id: "zinus",
    name: "Zinus",
    shortName: "Zinus",
    color: "#00A651",
    tagline: "Affordable sleep",
    types: ["bedding", "home"],
  },
  {
    id: "tuftandneedle",
    name: "Tuft & Needle",
    shortName: "Tuft & Needle",
    color: "#00B2A9",
    tagline: "Simple sleep",
    types: ["bedding", "home"],
  },
  {
    id: "leesa",
    name: "Leesa",
    shortName: "Leesa",
    color: "#E85D4C",
    tagline: "Bed-in-a-box",
    types: ["bedding", "home"],
  },
  {
    id: "buffy",
    name: "Buffy",
    shortName: "Buffy",
    color: "#F5F0E8",
    tagline: "Comforters & sheets",
    types: ["bedding", "home"],
  },
  {
    id: "tempurpedic",
    name: "Tempur-Pedic",
    shortName: "Tempur-Pedic",
    color: "#003087",
    tagline: "Memory foam sleep",
    types: ["bedding", "home"],
  },
];

export const BOOKS_HOME_RETAILER_IDS = BOOKS_HOME_RETAILERS.map((r) => r.id);
